### ISSUE TITLE
Break with error on build production

### ISSUE THREAD

**Issue by glamer** [Paol-imi/react-reparenting#12]
When I try to build a production with any mention of tag `<Reparentable>`, the app throwing error with the message "invariant failed".

**Comment by Paol-imi** [comment]
To solve your problem I need you to give me more information about the circumstances in which the error occurs (Sample code is welcome).
Does the error occur as a result of some action? 
Does it also happen in development mode?

**Comment by ttopkl** [comment]
I just tried to build an example from _https://codesandbox.io/s/react-reparenting-reparentable-rvfi4_
and get the same error

What did I do:
1. https://codesandbox.io/s/react-reparenting-reparentable-rvfi4
2. File -> Export to ZIP
3. npm install
4. npm run build
5. start a local server

**Comment by Paol-imi** [comment]
With the arrival of React 17, it will no longer be possible to use react-reparenting in production mode. The package (in its version 0.6.0) will continue to work with react 16 both in production and in development mode.

**Comment by pie6k** [comment]
So to be clear - in React 17 this lib is not an option anymore?

What is the reason for this?

**Comment by Paol-imi** [comment]
While no new features have been added in React 17, I will have to understand if and how the internals have been changed since 16. This is to try to avoid React internal misbehavior that would be impossible to debug.

I will work on an upcoming release to solve this problem.

**Comment by tarrencev** [comment]
any updates on this?

**Comment by Paol-imi** [comment]
The release has already been designed. Now I just have to write and publish it but I don't think I will have much free time for a few months. As soon as it is ready it will be available on github.

**Comment by coolbaluk** [comment]
I'm having the same issue even when downgrading to React 16. Does anybody have a working example ?

I presume that an internal dependency needs to be resolved to a specific version but I haven't been able to pinpoint it.

**Comment by Bartosz-L** [comment]
> I'm having the same issue even when downgrading to React 16. Does anybody have a working example ?
> 
> Edit: React 16 works only with `0.4.0` of this library.

I can confirm the solution works. Saved my day. Thank you!

**Comment by Paol-imi** [comment]
The new version of React-Reparenting should solve the problem, the API removed from version 0.4.0 are back available.
Please read carefully the warnings on the documentation site before using React-Reparenting in production code.
