### ISSUE TITLE
Invariant: Invariant failed

### ISSUE THREAD

**Issue by maciekglowacki** [Paol-imi/react-reparenting#13]
When moving from local hosting to real server, the library surprised us with this error:

![image](https://user-images.githubusercontent.com/29459845/103928600-59a74280-511c-11eb-875c-2db5f6bc8829.png)

Any ideas how to solve it?

Thanks, Maciek

**Comment by coolbaluk** [comment]
Check here to get things going: https://github.com/Paol-imi/react-reparenting/issues/12#issuecomment-744002280

We are waiting on a new version.

**Comment by maciekglowacki** [comment]
We managed to figure it out with that other issue. Waiting for the update/upgrade!

**Comment by Paol-imi** [comment]
Solved in #15.
