### ISSUE TITLE
Is it possible to do reparenting if another parent render conditional? 

### ISSUE THREAD

**Issue by mnikn** [Paol-imi/react-reparenting#14]
I want to reparent a element to another parent which need to conditional render. For example when router change, I want to reparent a element from A page to B page, but I found that if I do that, it will unmount. Here is the example, it is possible to do that? thanks!

![image](https://user-images.githubusercontent.com/12381740/106834461-7a899600-66d0-11eb-88d1-c4326100699a.png)

**Comment by Paol-imi** [comment]
In your example, the <Reparentable> components don't exist at the same time, so when you call the sendReparentable method it has no effect. You should get a warning, if you don't get it I'll have to investigate why.

To do what you ask, you have to manually remove the child from a parent, mount the new parent and insert the child into it.
You can do this with the ReparentableMap or with another component other than the <Reparentable>.

```js
const {Reparentable, ReparentableMap} = createReparentableSpace();

// Mount ParentA...
let ParentA = ReparentableMap.get("A"); // The Parent instance of the <Reparentable id="A">
let Child = ParentA.removeChild("ChildKey");

// Unmount ParentA...
// Mount ParentB...
let ParentB = ReparentableMap.get("B"); 
ParentB.addChild(Child, position);
```

**Comment by jrmyio** [comment]
A codesandbox example with for example a integration with react-router would really help, especially since the ReparentableMap is not mentioned in the react-reparenting docs (as far as i can see).

@mnikn did you end up using react-reparenting for your use-case? Do you happen to have a full example?

**Comment by mnikn** [comment]
I end up using react-reparenting, instead I try to rewrite my need reparenting component by pure dom js, and use dom api `appendChild` to move it.
