### ISSUE TITLE
React v17 support?

### ISSUE THREAD

**Issue by sophocode** [Paol-imi/react-reparenting#15]
The [docs](https://paol-imi.github.io/react-reparenting/docs/introduction#under-the-hood) currently say this package cannot be used in production build with React v17.

Is this still true or are there any updates?

Thanks :)

**Comment by jcampbell05** [comment]
Not sure if this is the case
https://github.com/Paol-imi/react-reparenting/issues/11

**Comment by Paol-imi** [comment]
The new version of React-Reparenting should solve the problem, the API removed from version 0.4.0 are back available.
Please read carefully the warnings on the documentation site before using React-Reparenting in production code.
