### ISSUE TITLE
Can't access the examples

### ISSUE THREAD

**Issue by nomanoff** [Paol-imi/react-reparenting#20]
I tried to have look at the examples on codesandbox but I'm facing some errors.
The examples on codesandbox seem to have some errors.
Is this also happening with yours too?
![image](https://user-images.githubusercontent.com/60359425/111246919-7abf6e80-864a-11eb-8951-1df75d723bac.png)

**Comment by paol-imi** [comment]
It seems a problem with babel, which should be a dependency of react-scripts.
The sandbox has not changed since I published the last version of react-reparenting, so I don't think it's a problem with the library.
I will investigate further.

**Comment by nomanoff** [comment]
Yes, that's I think so. When I removed the React import, it worked just fine.
