### ISSUE TITLE
Typescript errors on import

### ISSUE THREAD

**Issue by Stevenlee731** [Paol-imi/react-reparenting#8]
Hi! I'm receiving compile errors when im importing `Reparentable`. This is on a fresh new Create React App with Typescript.

`TypeScript error in /Users/node_modules/react-reparenting/dist/types/core/addChild.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type { Fiber } from 'react-reconciler';
      |             ^
    2 | /**
    3 |  * Add a child fiber in a parent fiber and return the index in which it is added.
    4 |  * The position can be chosen by providing a key (string) or by providing an index (number).`

Deleted the tsconfig file and everything started to work.

**Comment by Stevenlee731** [comment]
updating typescript from   "~3.7.2" to "^3.9.3" fixed the issue for me.

**Comment by brettinternet** [comment]
This is likely related to https://github.com/benmosher/eslint-plugin-import/issues/1667, however we might consider adding < 3.8 TypeScript support

**Comment by brettinternet** [comment]
This is likely related to https://github.com/typescript-eslint/typescript-eslint/issues/1436, however we might consider adding < 3.8 TypeScript support
